#!/bin/bash
name=$1
check(){
if [ -a ~/.gitconfig ]
then
        rm ~/.gitconfig
fi
if [ -a ~/.gitcookies ]
then
        rm ~/.gitcookies
fi

}
check_status(){
	cat ~/.gitconfig
	cat ~/.gitcookies
}
black_iss(){
git config --global user.email "black.di@bitland.corp-partner.google.com"
git config --global user.name "black.di"
touch ~/.gitcookies
chmod 0600 ~/.gitcookies

git config --global http.cookiefile ~/.gitcookies

tr , \\t <<\__END__ >>~/.gitcookies
.googlesource.com,TRUE,/,TRUE,2147483647,o,git-black.di.bitland.corp-partner.google.com=1/J_ShvkYm6HByvK-Ip4lpxFwpCkvheQ6FdN1_rYAGibI
__END__

}
black(){
git config --global user.email "black.di@bitland.com.cn"
git config --global user.name "black.di"
touch ~/.gitcookies
chmod 0600 ~/.gitcookies

git config --global http.cookiefile ~/.gitcookies

tr , \\t <<\__END__ >>~/.gitcookies
.googlesource.com,TRUE,/,TRUE,2147483647,o,git-black.di.bitland.com.cn=1/WdjvrszVDIbz3dJYoQ_PdvsKHuimmBAjWeWny8m6VLc
__END__

}
guohui(){
git config --global user.email "guohui.zhou@bitland.com.cn"
git config --global user.name "guohui.zhou"
touch ~/.gitcookies
chmod 0600 ~/.gitcookies

git config --global http.cookiefile ~/.gitcookies

tr , \\t <<\__END__ >>~/.gitcookies
.googlesource.com,TRUE,/,TRUE,2147483647,o,git-guohui.zhou.bitland.com.cn=1/qqiM7LS3-mdTrsH1jk6fcybLiBW6P76_32HhA9djhFE4H6QqvLn-7K8nKfRyCOcq
__END__
}
help1(){
echo -e "
Usage: gitconfig [name]

   black		:account for Birch Phoebe and Jerry
   black_iss		:account for Coral
   guohui               :account for hana master 
   status               :check git account status
   -h			:display current message
"
}
main(){
	case $name in
		black)
			check
			black
			;;
		black_iss)
			check
			black_iss
			;;
		guohui)
			check
			guohui
			;;
		status)
			check_status
			;;
		-h)
			help1
			;;
		*)
			echo "Wrong parameter"
	esac
}
main
